name = "Agutsin Server"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "892318c1535aa954bce146a75a7329c88b811e76a508d26c41817a72edae01ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
