name = "Agutsin Server"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08e331808f49ef5b82f18d124cb7b3ef952850a37a3c31a23915428198ebb0f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
